services:
  # Redis - Key-value Store
  redis:
    container_name: redis
    image: redis:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $REDIS_PASSWORD ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    networks:
      - default
    entrypoint: redis-server --appendonly yes --requirepass $REDIS_PASSWORD --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - $DOCKERDIR/appdata/redis/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
