create database DATABASE_NAME_PLACEHOLDER;
CREATE USER 'DATABASE_USERNAME_PLACEHOLDER' IDENTIFIED BY 'DATABASE_PASSWORD_PLACEHOLDER';
GRANT ALL ON `DATABASE_NAME_PLACEHOLDER%`.* TO 'DATABASE_USERNAME_PLACEHOLDER';
flush privileges;
quit