services:
  # Guacamole - Remote desktop, SSH, on Telnet on any HTML5 Browser
  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$GUACAMOLE_PORT:8080"
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mariadb
      MYSQL_PORT: 3306
      MYSQL_DATABASE: guacamole
      MYSQL_USER_FILE: /run/secrets/guac_mariadb_user
      MYSQL_PASSWORD_FILE: /run/secrets/guac_mariadb_password
    secrets:
      - guac_mariadb_user
      - guac_mariadb_password
    # DOCKER-LABELS-PLACEHOLDER