services:
  # Homarr - Application Dashboard
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
      # - t3_proxy
      - socket_proxy
    ports:
      - "$HOMARR_PORT:7575"
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - $DOCKERDIR/appdata/homarr/configs:/app/data/configs
      - $DOCKERDIR/appdata/homarr/icons:/app/public/icons
      - $DOCKERDIR/appdata/homarr/data:/data
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
    # DOCKER-LABELS-PLACEHOLDER