services:
  # Homebridge - iOS HomeKit API
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homebridge
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
      # - t3_proxy
    ports:
      - "$HOMEBRIDGE_PORT:8581"
    volumes:
      - $DOCKERDIR/appdata/homebridge:/homebridge
    # DOCKER-LABELS-PLACEHOLDER